# Generated by Django 5.2.7 on 2026-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_module_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('course', 'Course Completion'), ('internship', 'Internship'), ('workshop', 'Workshop'), ('project', 'Live Project')], default='course', max_length=20, verbose_name='Certificate Type')),
                ('course_name', models.CharField(help_text="e.g. 'Python Full Stack Development'", max_length=200)),
                ('image', models.ImageField(help_text='Upload certificate image/scan', upload_to='certificates/')),
                ('description', models.TextField(blank=True, help_text='Optional tagline shown under the certificate')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Python Bootcamp – March 2025'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short caption shown under the photo (optional)')),
                ('image', models.ImageField(help_text='Upload workshop photo', upload_to='workshop_photos/')),
                ('event_date', models.DateField(blank=True, help_text='Date the workshop was held (optional)', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workshop Photo',
                'verbose_name_plural': 'Workshop Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
