# Generated by Django 5.2.7 on 2026-06-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_certificate_workshopphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreview',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to say')], default='M', help_text='Used for default anime avatar if no custom image is uploaded', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
