# Generated by Django 5.2.7 on 2026-07-01 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'Django, Bootstrap, PostgreSQL, REST API'", max_length=400),
        ),
        migrations.CreateModel(
            name='ServiceDemoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'E-commerce Demo', 'Portfolio Demo'", max_length=150)),
                ('url', models.URLField(help_text='Full link to the live demo site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_links', to='main.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
