# Generated by Django 5.2.7 on 2026-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_service_technologies_servicedemolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedemolink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
