# Generated by Django 5.2.7 on 2026-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_servicedemolink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedemolink',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
