# Generated by Django 5.2.7 on 2026-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_servicedemolink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedemolink',
            name='url',
            field=models.URLField(blank=True, help_text='Full link to the live demo site', null=True),
        ),
    ]
