# Generated by Django 5.2.7 on 2026-07-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_servicedemolink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedemolink',
            name='category',
            field=models.CharField(blank=True, help_text="e.g. 'Education', 'CRM', 'Hotel', 'Portfolio' — used for Live Demo filters", max_length=100),
        ),
        migrations.AddField(
            model_name='servicedemolink',
            name='description',
            field=models.CharField(blank=True, help_text='Short one-line description shown on the Live Demo card', max_length=300),
        ),
        migrations.AddField(
            model_name='servicedemolink',
            name='is_featured',
            field=models.BooleanField(default=True, help_text="Show this on its Service's detail page (uncheck to keep it Live-Demo-page-only)"),
        ),
        migrations.AddField(
            model_name='servicedemolink',
            name='technologies',
            field=models.CharField(blank=True, help_text="Comma-separated, e.g. 'HTML, CSS, JS'", max_length=300),
        ),
    ]
