# Generated by Django 5.2.13 on 2026-07-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_internship_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='coursebooking',
            name='payment_type',
        ),
    ]
