# Generated by Django 5.2.7 on 2026-07-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_internship_image'),
        ('main', '0022_processstep_servicefaq_servicefeature'),
    ]

    operations = [
    ]
