# Generated by Django 5.2.13 on 2026-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_coursebooking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
