# Generated by Django 5.2.13 on 2026-07-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_coursebooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
