# Generated by Django 5.2.7 on 2026-07-04 04:57

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_siteoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoffer',
            name='description',
            field=models.TextField(),
            ),
    ]
