# Generated by Django 5.2.13 on 2026-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_workshopregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingWorkshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('image', models.ImageField(upload_to='upcoming_workshops/')),
            ],
        ),
    ]
