# Generated by Django 5.2.7 on 2026-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_siteoffer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_offers/'),
        ),
    ]
