# Generated by Django 5.2.13 on 2026-07-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_coursebooking_amount_and_more'),
        ('main', '0026_siteoffer_image'),
    ]

    operations = [
    ]
