# Generated by Django 5.2.13 on 2026-07-08 04:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_upcomingworkshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingworkshop',
            name='event_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingworkshop',
            name='location',
            field=models.CharField(default='online', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingworkshop',
            name='registration_info',
            field=models.CharField(default='Free Registration', max_length=200),
            preserve_default=False,
        ),
    ]
