# Generated by Django 5.2.13 on 2026-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_merge_20260705_1242"),

    ]

    operations = [
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_image", models.ImageField(upload_to="placements/")),
                ("company_name", models.CharField(max_length=100)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("job_role", models.CharField(max_length=100)),
                ("package", models.CharField(max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("placed_year", models.PositiveIntegerField()),
                ("course", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
