# Generated by Django 5.2.13 on 2026-07-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_upcomingworkshop_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingworkshop',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upcomingworkshop',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='upcomingworkshop',
            name='registration_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
