# Generated by Django 5.2.7 on 2026-07-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_coursebooking_amount'),
        ('main', '0028_placement'),
    ]

    operations = [
    ]
