# Generated by Django 5.2.13 on 2026-07-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_upcomingworkshop_event_time_and_more'),
        ('main', '0029_merge_0024_alter_coursebooking_amount_0028_placement'),
    ]

    operations = [
    ]
