# Generated by Django 5.2.13 on 2026-07-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_democategory_alter_career_id_alter_certificate_id_and_more'),
        ('main', '0030_merge_20260709_1448'),
    ]

    operations = [
    ]
